name: road2quant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - jupyterlab
  - ipykernel
  - pytest
  - pytest-cov
  - black
  - ruff
  - mypy
  - arch          # GARCH
  - cvxpy         # convex optimisation for portfolios
  - quantlib      # derivatives pricing
  - pip:
      - filterpy
      - yfinance
      - pandas-datareader
      - -e .
